#include <vector>
#include <algorithm>

class Solution {
public:
    int nthUglyNumber(int n) {
        // We handle the edge case where n is non-positive, though constraints
        // usually ensure n >= 1.
        if (n <= 0) {
            return 0;
        }

        // Create a vector to store the ugly numbers in sequence.
        // dp[i] will store the (i+1)-th ugly number.
        std::vector<int> dp(n);

        // The first ugly number is always 1.
        dp[0] = 1;

        
        int p2 = 0;
        int p3 = 0;
        int p5 = 0;

        // Loop to fill the dp array from the second element onwards.
        for (int i = 1; i < n; ++i) {
            // Calculate the next potential ugly number from each prime factor sequence.
            int next_ugly_by_2 = dp[p2] * 2;
            int next_ugly_by_3 = dp[p3] * 3;
            int next_ugly_by_5 = dp[p5] * 5;

            // The next ugly number is the minimum of these three candidates.
            dp[i] = std::min({next_ugly_by_2, next_ugly_by_3, next_ugly_by_5});

            // Advance the pointer(s) that generated the new minimum ugly number.
            // We use separate 'if' statements because a single number can be
            // generated by multiple paths (e.g., 6 = 2 * 3 = 3 * 2). In such
            // cases, we need to advance all relevant pointers.
            if (dp[i] == next_ugly_by_2) {
                p2++;
            }
            if (dp[i] == next_ugly_by_3) {
                p3++;
            }
            if (dp[i] == next_ugly_by_5) {
                p5++;
            }
        }

        // The n-th ugly number is at the last position of our dp array.
        return dp[n - 1];
    }
};
